
dao_meta = DaoMake::Project( "DaoMeta" ) 

daovm = DaoMake::FindPackage( "Dao", $REQUIRED )

if( daovm == none ) return

dao_meta_objects = DaoMake::Objects( { "dao_meta.c" } )
dao_meta_lib     = dao_meta.AddSharedLibrary( "dao_meta", dao_meta_objects )

dao_meta_lib.UsePackage( daovm )
dao_meta_lib.EnableDynamicLinking()

