
all:
	-cd auxlib && make
	-cd syslib && make
	-cd math && make
	-cd string && make
	-cd reflection && make
	-cd network && make
	-cd web && make
	-cd os && make
#	-cd DaoCXX && make
#	-cd DaoJIT && make
