
all:
	-cd auxlib && $(MAKE)
	-cd syslib && $(MAKE)
	-cd math && $(MAKE)
	-cd string && $(MAKE)
	-cd meta && $(MAKE)
	-cd net && $(MAKE)
	-cd web && $(MAKE)
	-cd os && $(MAKE)
#	-cd DaoCXX && $(MAKE)
#	-cd DaoJIT && $(MAKE)
