
modules = DaoMake::Project( "DaoModules" );

daovm = DaoMake::FindPackage( "Dao", $REQUIRED )

if( daovm == none ) return

modules.Install( "addpath.dao", daovm.GetPath( "MOD-PATH" ) )

if( DaoMake::IsDir( "DaoJIT" ) ) modules.AddDirectory( "DaoJIT", "DaoJIT" );
