
PLATS = linux macosx freebsd mingw minix beos haiku

MODE ?= release
ROOT ?= /usr/local
SRCDIR ?= .
SUFFIX ?=

$(PLATS) :
	cd $(SRCDIR)/tools/daomake && $(MAKE) -f Makefile.bootstrap $@
	$(SRCDIR)/tools/daomake/daomake --mode $(MODE) --platform $@ --option-ROOT-PATH $(ROOT) $(SRCDIR)
	$(MAKE) -f Makefile$(SUFFIX)

