
PLATS = linux macosx freebsd mingw minix

MODE ?= release
ROOT-PATH ?= /usr/local

$(PLATS) :
	cd tools/daomake && $(MAKE) -f Makefile.bootstrap $@
	./tools/daomake/daomake --mode $(MODE) --platform $@ --option-ROOT-PATH $(ROOT-PATH)
	$(MAKE) -f Makefile$(SUFFIX)

