
daotests = DaoMake::Project( "DaoTests" ) 

daovm = DaoMake::FindPackage( "Dao", $REQUIRED )

if( daovm == none ) return

daotests.AddTest( "Example", "examples.dao" )

daotests.AddTest( "Lexer",  "test_lexer.dao" )
daotests.AddTest( "Parser", "test_parser.dao" )

daotests.AddTest( "Numbers", "test_numbers.dao" )
daotests.AddTest( "Strings", "test_strings.dao" )

daotests.AddTest( "Routine", "test_routine.dao" )

daotests.AddTest( "Misc", "test_misc.dao" )
