
daotests = DaoMake::Project( "DaoTests" ) 

daovm = DaoMake::FindPackage( "Dao", $REQUIRED )

if( daovm == none ) return

chartype_objs = DaoMake::Objects( { 'dao_CharType.c' } )
chartype_lib = daotests.AddSharedLibrary( 'CharType', chartype_objs )
chartype_lib.UsePackage( daovm )
chartype_lib.EnableDynamicLinking()

daotests.AddTest( "Example", "examples.dao" )

daotests.AddTest( "Lexer",  "test_lexer.dao" )
daotests.AddTest( "Parser", "test_parser.dao" )

daotests.AddTest( "Numbers", "test_numbers.dao" )
daotests.AddTest( "Strings", "test_strings.dao" )

test_enum = daotests.AddTest( "EnumSymbol", "test_enum_symbol_def.dao" )
test_enum.AddTest( "test_enum_symbol_type.dao" )

test_routine = daotests.AddTest( "Routine", "test_routine.dao" )
test_routine.AddTest( "test_coroutine.dao" )
test_routine.AddTest( "test_anonymous_routine.dao" )

test_class = daotests.AddTest( "Class", "test_class_inheritance.dao" )

test_interface = daotests.AddTest( "Interface", "test_interface.dao" )

test_regex = daotests.AddTest( "Regex", "test_regex_char_class.dao" )
test_regex.AddDependency( chartype_lib )

daotests.AddTest( "Misc", "test_misc.dao" )
