
all:
	-cd md5 && $(MAKE)
	-cd tokenize && $(MAKE)
	-cd xxtea && $(MAKE)
	-cd format && $(MAKE)

clean:
	-cd md5 && $(MAKE) clean
	-cd tokenize && $(MAKE) clean
	-cd xxtea && $(MAKE) clean
	-cd format && $(MAKE) clean
